apiVersion: v1
kind: Service
metadata:
  name: user-embedding-service
  namespace: recsys
spec:
  selector:
    app: user-embedding
    
  ports:
      - name: metrics       # <--- THIS NAME MUST MATCH THE SERVICEMONITOR
        protocol: TCP
        port: 80            # The port exposed by the service
        targetPort: 8000