apiVersion: v1
kind: Service
metadata:
  name: user-embedding-service
  namespace: recsys
spec:
  selector:
    app: user-embedding
  ports:
    - protocol: TCP
      port: 80      # Retrieval service calls http://user-embedding-service
      targetPort: 8000