apiVersion: v1
kind: ConfigMap
metadata:
  name: data-service-config
data:
  DB_HOST: "postgres-service"
  REDIS_HOST: "redis-service"
  FEAST_REPO_PATH: "/app/feature_repo"
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secrets
type: Opaque
data:
  # Base64 for 'postgres_pass'
  DB_PASSWORD: cG9zdGdyZXNfcGFzcw==