apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: recsys
spec:
  selector:
    service: data-api
  ports:
    - name: metrics
      protocol: TCP
    - port: 80
      targetPort: 8000